#:schema https://raw.githubusercontent.com/usecannon/cannon/refs/heads/dev/packages/lsp/src/schema.json

name = "cow-omnibus-test"
version = "0.1.0"

[var.main]
salt = "Futons in Tokyo!"
wrappedNativeToken = "0x4200000000000000000000000000000000000006"


initialOwner = "0x5002Ee88591876C148443cdED7a6D2e466B0147a"
initialManager = "0x5002Ee88591876C148443cdED7a6D2e466B0147a"

currentOwner = "0x5002Ee88591876C148443cdED7a6D2e466B0147a"
currentManager = "0x5002Ee88591876C148443cdED7a6D2e466B0147a"

[clone.settlement]
source = "cow-settlement:2.0.2"
target = "cow-settlement:2.0.2"
#options.salt = "<%= settings.salt %>"
options.owner = "<%= settings.initialOwner %>"
options.manager = "<%= settings.initialManager %>"

[clone.ethflow]
source = "cow-ethflow:1.0.2"
target = "cow-ethflow:1.0.2"
options.wrappedNativeToken = "<%= settings.wrappedNativeToken %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

depends = ["clone.settlement"]

[clone.helpers]
source = "cow-helpers:1.0.0"
target = "cow-helpers:1.0.0"
#options.salt = "<%= settings.salt %>"

[clone.trampoline]
source = "cow-hooks-trampoline:1.0.0"
target = "cow-hooks-trampoline:1.0.0"
#options.salt = "<%= settings.salt %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

[clone.composableCow]
source = "cow-composable:1.0.0"
target = "cow-composable:1.0.0"
#options.salt = "<%= settings.salt %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
depends = ["clone.settlement"]

[clone.shed]
source = "cow-shed:2.0.0"
target = "cow-shed:2.0.0"
#options.salt = "<%= settings.salt %>"
options.composableCow = "<%= composableCow.ComposableCoW.address %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

[clone.vouchRegister]
source = "cow-vouch-register:1.0.0"
target = "cow-vouch-register:1.0.0"
#options.salt = "<%= settings.salt %>"

[clone.flashLoanRouter]
source = "cow-flash-loan-router:1.0.0"
target = "cow-flash-loan-router:1.0.0"
#options.salt = "<%= settings.salt %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

depends = ["clone.settlement"]

[clone.fee]
source = "cow-fee:1.0.0"
target = "cow-fee:1.0.0"
options.wrappedNativeToken = "<%= settings.wrappedNativeToken %>"
options.cowSettlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

depends = ["clone.settlement"]

[invoke.setAuthenticatorManager]
target = "settlement.Authenticator"
from = "<%= settings.initialOwner %>"
func = "setManager"
args = ["<%= settings.currentManager %>"]

# TODO: cannon issue: its not possible to do this due to ABI insufficiency
#[invoke.setAuthenticatorOwner]
#target = "settlement.Authenticator"
#from = "<%= settings.initialOwner %>"
#func = "setAdmin"
#args = ["<%= settings.currentOwner %>"]

# having this dependency prevents needing to control both the `settings.currentOwner`, reducing a required signer for deployment.
#depends = ["invoke.setAuthenticatorManager"]
